### ISSUE TITLE
in sample forecast 

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/mlforecast#106]
## Description

Not sure how to make in sample predictions using the current library. 
To use it together with hierarchicalforecast library, and to reconcile, y_fitted_df is required, which has one of its columns predictions made with the model for the training data (unique_id, ds, y, model predictions are all the columns needed )   
## Reproducible example

In the current set up, there is fit, and predict, where predict only needs to receive as input, the horizon.
Wonder how to make predictions for the training dataset . 

```python
# code goes here
```

![image](https://user-images.githubusercontent.com/12494156/226577262-151b9e26-945b-430d-a596-b64b790da7c6.png)

https://nixtla.github.io/hierarchicalforecast/examples/australianprisonpopulation.html
```python
# Stacktrace
```

## Environment info
Install method (pip, conda, github): 

Package version:

**Comment by jmoralez** [comment]
Hi @iamyihwa, we currently don't have a way to do this automatically but you can do the following:
```python
from mlforecast import MLForecast
from mlforecast.utils import generate_daily_series
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

# data setup
series = generate_daily_series(20).reset_index()
id_col = 'unique_id'
time_col = 'ds'
target_col = 'y'

# preprocess
fcst = MLForecast(
    models=[
        RandomForestRegressor(n_estimators=10),
        LinearRegression(),
    ],
    freq='D',
    lags=[7, 14],
    date_features=['dayofweek'],
)

# prep here has the original input + the features
prep = fcst.preprocess(series, id_col, time_col, target_col)
X, y = prep.drop(columns=[id_col, time_col, target_col]), prep[target_col]
# we can call fit models to train each of our models with this X and y
fcst.fit_models(X, y)

# compute in sample predictions
in_sample_pred = prep[[id_col, time_col, target_col]].copy()
for name, model in fcst.models_.items():
    in_sample_pred[name] = model.predict(X)
```
You should be able to use `in_sample_pred` as the `Y_fitted_df` in the example.

Please let us know if you have further doubts.

**Comment by iamyihwa** [comment]
Thank you very much @jmoralez ! The example is clear !!
