### ISSUE TITLE
Size of cross-validation windows used to calibrate the intervals

### ISSUE THREAD

**Issue by Lycher2** [Nixtla/mlforecast#126]
Hello, can you please explain why the size of the window for cross-validation of values for conformal interval calibration depends on the length of the prediction interval. For example why I can't have a train length 1000, n_windows = 50, window_size = 50. And then predict the value 1 point ahead ( test length 1 or horizon =  1) ?
![image](https://user-images.githubusercontent.com/99182431/236129222-db6a3f26-1a1a-478c-aa92-3fc136d18a36.png)

**Comment by FedericoGarza** [comment]
hey @Lycher2! Thanks for using mlforecast.

Currently, the prediction intervals are calibrated for each step on the horizon. So, for example, if you want to predict 7 steps, `window_size=7` will calculate the absolute errors for `h=1`, `h=2`, ..., `h=7` using `n_windows`. This way the prediction intervals will reflect the uncertainty associated with each step. If you want to estimate the uncertainty globally (the same for each step) you can use `window_size=1`. 

I agree that if `horizon<=window_size`, we should be able to calculate the prediction intervals for `horizon`. So we will work on including this option.

**Comment by Lycher2** [comment]
Thanks for the quick response. I hope to be able to add this feature soon. If I get any ideas and implementation, I'll try to share.
