### ISSUE TITLE
[Core, Discussion] Make arguments compatible with the nixtlaverse

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/mlforecast#149]
### Description

Certain methods within `MLForecast` accept similar arguments to other components within the nixtlaverse (`StatsForecast` and `MLForecast`), but these arguments are named differently. We aim to standardize these argument names for better consistency across the package. Specifically:

- In the `fit` method, the argument `data` should be renamed to `df`.
- In the `predict` method, the argument `horizon` should be renamed to `h`, `new_data` should be changed to `new_df`, and the naming of `dynamic_dfs` needs discussion (it's currently referred to as `X_df` in `StatsForecast` and `futr_df` in `NeuralForecast`).
- In the `cross_validation` method, `data` should be renamed to `df`, and `window_size` should be changed to `h`.

**Comment by sotte** [comment]
I also raised this point here: https://github.com/Nixtla/statsforecast/discussions/493
