### ISSUE TITLE
[Core] Add parameter to use the ID as a feature

### ISSUE THREAD

**Issue by tblume1992** [Nixtla/mlforecast#157]
### Description

Currently you have to create a copy of the column and pass it in like: 
```
import lightgbm as lgb
from mlforecast import MLForecast
from mlforecast.utils import generate_daily_series


series = generate_daily_series(100, equal_ends=True, n_static_features=2, static_as_categorical=True)

series['my_id_col'] = series['unique_id'].copy()

mlf = MLForecast(
    models=lgb.LGBMRegressor(),
    freq='D',
    lags=[7],
)
mlf.fit(series, static_features=['my_id_col', 'static_0', 'static_1'])

preds = mlf.predict(12)
```
If this could be a boolean parameter passed to fit or object creation that would make it a smoother user experience.

### Use case

Using the ID as a feature can increase performance in many scenarios or at least alleviates the need for as many window functions.

**Comment by jmoralez** [comment]
Hey @tblume1992, thanks for raising this. Allowing this seemed to complicate the codebase a bit but I'll take another look, ideally we'd like to be able to use the same column as the id and as a static feature, to reduce memory usage.

I'll post any updates here.

**Comment by jmoralez** [comment]
#161 allows passing the same column as id_col and as a static feature.
