### ISSUE TITLE
[<Componente de la biblioteca: Modelo|Core|etc... >]

### ISSUE THREAD

**Issue by Naren8520** [Nixtla/mlforecast#159]
### What happened + What you expected to happen

Hello Nixtla team.

I am making a Machine Learning model, but it turns out that I have the following problem when I make the predictions with the predict method by adding the level(confidence interval) parameter, it gives me an error:

<img width="1153" alt="Captura de pantalla 2023-06-28 a la(s) 12 07 18 a  m" src="https://github.com/Nixtla/mlforecast/assets/71158095/4b2554fa-561a-4336-bd8e-a18e0c21032d">

### Versions / Dependencies

python 3.10.11

### Reproduction script
```python
mlf = MLForecast(
    models=modelos,
    freq='W',  # Nuestra serie tiene frecuencia mensual 
    lags=[6 * (i+1) for i in range(7)],
    lag_transforms={
        1: [expanding_mean],
        48: [(rolling_mean, 48)]},
    differences=[1], 
    date_features=["year", "week"] # Datos de estacionalidad
)

mlf.fit(df1, id_col='unique_id', time_col='ds', target_col='y',prediction_intervals=PredictionIntervals(n_windows=5, window_size=18))

levels = [50, 80, 95]
preds = mlf.predict(18, level=levels)# Predicimos los próximos 18 meses
[preds.head()
```
### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Thanks for using mlforecast. I think the frequency may be wrong, since you're getting an empty dataframe with the cross validation results, are you sure it's weekly?
