### ISSUE TITLE
dynamics_df in predict method doesn't work as expected  

### ISSUE THREAD

**Issue by Chiu-Huang** [Nixtla/mlforecast#168]
### What happened + What you expected to happen

I think when exogenous variable (X) is presented, predict method simply uses the first row of X (first observation) instead of the last row (latest observation), hence 
preds = fcst.predict(7, dynamic_dfs=[X]) provides the same value as 
preds = fcst.predict(7) even X is not provided.  

### Versions / Dependencies

- Python == 3.10.12
- mlforecast == 0.7.4

### Reproduction script
```python
from mlforecast.utils import generate_daily_series
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from mlforecast import MLForecast
import numpy as np 
series = generate_daily_series(
    n_series=1,
    max_length=100,
    n_static_features=1,
    static_as_categorical=False,
    with_trend=True
)
series['important_col'] = series['y'] + np.random.normal(0, 1, len(series))
df_train, df_test = train_test_split(series, test_size=12, shuffle=False)

fcst = MLForecast(
    models=[LinearRegression(), ], 
    freq='M',
    lags=[1, 2, 3],
)
fcst.fit(df_train)
yhat = fcst.predict(12, dynamic_dfs = [df_test])['LinearRegression'].values
yhat_without_X = fcst.predict(12, )['LinearRegression'].values

np.testing.assert_allclose(yhat, yhat_without_X)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hi, thanks for using mlforecast. I believe this is the same as #109, can you try setting the static_features argument of the fit method to match the ones of your data? If none are static then you need to pass an empty list.

**Comment by Chiu-Huang** [comment]
thanks for the urgent feedback and thanks for providing the library! It works.
