### ISSUE TITLE
Error during conformal prediction -- cannot reshape array

### ISSUE THREAD

**Issue by ruchitmehta87** [Nixtla/mlforecast#170]
Getting `ValueError: cannot reshape array of size 65 into shape (3,1,24)` with `PredictionIntervals(n_windows=3, window_size=24)`. This is happening with only some datasets. Is this due to CV results not having enough datapoints ?

**Comment by jmoralez** [comment]
Hi. Yes, this means that you have series with length less than 24 * 3, so in some fold there are less series used to train (and predict). I'll try to make this error show up sooner.

**Comment by jmoralez** [comment]
I believe this was fixed with #160, which helps detect this issue sooner. Feel free to reopen if you feel it's not solved.
