### ISSUE TITLE
Request for Implementation of fill_gaps Function to Handle Time Series with Gaps

### ISSUE THREAD

**Issue by mairon-chaves** [Nixtla/mlforecast#178]
### Description

Hi

First of all, I would like to congratulate everyone at Nixtla for the implementations, your ecosystem is really good.

I hope this message finds you well. I am reaching out to request the implementation of the fill_gaps functio, similar to the one available in the R tsibble library, which allows us to handle time series that have gaps in the dates, as well as different start and end dates between time series.

The fill_gaps function is an extremely useful tool for dealing with time series, especially in situations where data is collected non-uniformly, resulting in implicit missing values in the series. It offers the flexibility to fill these gaps with explicit values, making time series analysis more accurate and efficient.

Follow the link to the help page: https://tsibble.tidyverts.org/reference/fill_gaps.html

The library timetk has a similar tool, called pad_by_time()  : https://search.r-project.org/CRAN/refmans/timetk/html/pad_by_time.html

### Use case

Key Features and Importance of the fill_gaps function:

Gap Filling: The function allows us to fill gaps in time series with default NA values, helping to maintain the data structure and ensuring that no values are overlooked during analysis.

Support for Multiple Time Series (panel data): The function can handle multiple time series, where each series may have its own start and end dates, as well as possible gaps in observations.

Flexibility of Filling: It enables users to specify custom values to replace implicit missing values, giving the freedom to choose the most suitable method for filling.

Handling Unbalanced Panel Data: When time series have different time periods, the function can appropriately fill the gaps, ensuring that each series is treated independently, even if their observations are not aligned.

**Comment by jmoralez** [comment]
Hi @mairon-chaves, we just released the utilsforecast library, which has the [fill_gaps function](https://nixtla.github.io/utilsforecast/preprocessing.html#fill_gaps). Can you give it a try and let us know what you think?
