### ISSUE TITLE
Log, log1p, and box-cox target transformations

### ISSUE THREAD

**Issue by elisevansartefact** [Nixtla/mlforecast#184]
### Description

Add Log, Log1p, and Box Cox options for the target_transform argument of MLForecast

### Use case

Similar to how Differences and LocalStandardScaler can be added as a target_transform argument of MLForecast() to transform and un-transform the target variable when forecasting, it would be great to have the same thing for Log, Log(x+1) (similar to np.log1p), and Box Cox transforms

**Comment by jmoralez** [comment]
Hey @elisevansartefact, thanks for raising this. Would the [GlobalSklearnTransfomer](https://nixtla.github.io/mlforecast/docs/target_transforms_guide.html#globalsklearntransformer) solve your issue?
