### ISSUE TITLE
MLForecast: Create a MLForecast object with pre-trained models for inference deployments

### ISSUE THREAD

**Issue by pljnagda** [Nixtla/mlforecast#186]
### Description

Allow creation of a MLForecast with pre-trained models. 

```
class MLForecast:
    def __init__(
        self,
        models: Models,
        freq: Optional[Freq] = None,
        lags: Optional[Lags] = None,
        lag_transforms: Optional[LagTransforms] = None,
        date_features: Optional[Iterable[DateFeature]] = None,
        differences: Optional[Iterable[int]] = None,
        num_threads: int = 1,
        target_transforms: Optional[List[BaseTargetTransform]] = None,
        is_models_pretrained: bool: = False,
    ):
```

### Use case

Example use case would be a real time inference deployment where each server needs to create a MLForecast object on startup for inference without the need to fit the models.

**Comment by jmoralez** [comment]
Hey @pljnagda, we usually recommend using pickle ([example](https://github.com/Nixtla/mlforecast/discussions/116#discussioncomment-5575771)). Would that not work for your use case?
