### ISSUE TITLE
Add cross validation retrain frequency as an option

### ISSUE THREAD

**Issue by joshdunnlime** [Nixtla/mlforecast#188]
### Description

Allow retraining to be at a lower frequency than the forecasts. E.g. Forecast 24 hours/time steps ahead but retrain weekly.

```
mlf.cross_validation(windows_size=24, retrain=7, n_windows=3)
```

### Use case

We might have a business case where we train a model predict the day ahead at hourly resolution. Currently, I can cross validate this with `windows_size=24` and selecting the right length of the dataframe and number of windows. Great!

However, if we have a process that retrains once a week and is called to predict one day ahead (using new values for y and exogenous variables gained within the week), there is no way to use the `cross_validation` method.

I would propose an enhancement such that `retrain=7` to reference retraining the model every 7 windows.  Alternatively, `retrain=7 * 24` could be used if working with the frequency of the data is preferred. 

This would be a more realistic test of how the model would perform in real life.

**Comment by jmoralez** [comment]
Hey @joshdunnlime, thanks for using mlforecast. So in this example you want to refit the model every week but you only have 3 windows (3 days). I guess you want to forecast for example 4 weeks (28 windows) and retrain every week, right? I think we should have `n_windows > retrain`, so if your example was `mlf.cross_validation(window_size=24, retrain=7, n_windows=28)` I think it'd be straightforward to implement.

**Comment by joshdunnlime** [comment]
Hi @jmoralez
Thanks for the amazingly fast reply. I can see you've already started a PR for this as well. You guys are doing some incredible stuff!

Yes, my mistake, I wasn't clear on the n_windows. In your case it seems they refer to the forecast windows E.g. 7 test windows are bundled into one retrain. The 3 above was 3 retrain bundles. I believe your notation is more consistent with the rest of your API.

Thanks again!

**Comment by joshdunnlime** [comment]
FYI - This is similarly supported in [skforecast](https://skforecast.org/0.9.1/api/model_selection#skforecast.model_selection.model_selection.backtesting_forecaster).

**Comment by joshdunnlime** [comment]
Install worked and functionality works as expected. Amazing!! thanks
