### ISSUE TITLE
Exogenous variables example

### ISSUE THREAD

**Issue by braaannigan** [Nixtla/mlforecast#200]
### Description

There isn't much info in the docs on working with exog variables where these variables are forecasts at a given horizon. A real life example is predicting electricity demand at horizons of say 1 to 5 hours ahead where we. While we also have weather forecasts 1 to 5 hours ahead. 

I've spent some time putting together a minimal working example. However, I don't think the approach I'm using is correct as the results are poor in my actual data with this approach.

I would like your help to understand how to do this correctly. If you can help me understand this better I could also do a PR to add a similar example to the docs.

Setting up even a MWE takes a bit of time so I've made it as a notebook. Github doesn't allow uploading notebooks with issues. Should I make it a PR so you can see what the problem is?

**Comment by jmoralez** [comment]
Hey @braaannigan, thanks for using mlforecast. I believe this is covered in [this example](https://nixtla.github.io/mlforecast/forecast.html#dynamic-features). Can you please take a look at let us know if something is missing?

**Comment by braaannigan** [comment]
Hi @jmoralez - thanks for that. I hadn't seen the part about calling predict for each horizon separately, I'll have a go and let you know.

Thanks for all your work on this great library!

**Comment by braaannigan** [comment]
Hi @jmoralez - I see how that works now, I'll close the issue
