### ISSUE TITLE
MLForecast.preprocess changes self.ts.max_horizon

### ISSUE THREAD

**Issue by ltsaprounis** [Nixtla/mlforecast#201]
### What happened + What you expected to happen

The `MLForecast.preprocess` method changes the state of the class (the `MLForecast.ts.max_horizon` attribute) resulting in some unexpected behaviour (see code snippet below). This is not a massive bug, but it was a bit confusing to isolate. I thought that `preprocess` is not supposed to change the state, similar to `predict` or `transform` in `scikit-learn` rules.

The error is the same as the one reported in #195 so maybe they're related

### Versions / Dependencies

most recent release: `mlforecast==0.9.2`

### Reproduction script

```python
import pandas as pd
from mlforecast import MLForecast
from sklearn.linear_model import LinearRegression

df = pd.read_csv('https://datasets-nixtla.s3.amazonaws.com/air-passengers.csv', parse_dates=['ds'])

fcst = MLForecast(
    models=[LinearRegression()],
    freq='MS',
    lags=[12],
)

fcst.fit(df, max_horizon=12)
print(fcst.ts.max_horizon) # prints 12

# preprocess changes the state (i.e. the value of self.max_horizon) here
fcst.preprocess(df)
print(fcst.ts.max_horizon) # prints None

preds = fcst.predict(12,) # raises AttributeError: 'list' object has no attribute 'predict'
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @ltsaprounis, thanks for using mlforecast. `MLForecast.preprocess` is kind of fit_transform in scikit-learn terms (actually it calls `MLForecast.ts.fit_transform`), but it works on the data only (feat eng and saving stuff for the predict step), not models, so fit didn't seem appropriate, sorry for the confusing naming. Do you think we could improve something to avoid this confusion?

**Comment by ltsaprounis** [comment]
Thanks for the clarification @jmoralez! Makes sense now. Simply adding a sentence like above to the docs would do I think, just in case someone gets confused like me. Maybe something like: 
"Calling `preprocess` is similar to scikit-learn's `fit_transform` and will write to self."

In my case I had a forgotten debug print with `preprocess` that I was using to check that all the features were created appropriately and when I tried to change to the direct strategy (with max_horizon) this was still there after fit and it was breaking things 🙈 

Closing the issue since it's not really a bug.

**Comment by jmoralez** [comment]
I think we can add a check before predicting, when `max_horizon` is set each of the trained models is a list (one model for each horizon), so they look like `{'model_name': [model_h1, model_h2, ...]}`. I think we can raise an error when the models are a list but `max_horizon` is `None` or the other way around. Thanks for raising this!
