### ISSUE TITLE
mlforecast: Allow to calculate the full Conformal Prediction Distribution

### ISSUE THREAD

**Issue by EtienneT** [Nixtla/mlforecast#203]
### Description

It would be really interesting to be able to get the full conformal production distribution (equivalent of the CDF).  A bit like this article describe: https://valeman.medium.com/how-to-predict-full-probability-distribution-using-machine-learning-conformal-predictive-f8f4d805e420, or this one which is CatBoost specific but still: https://towardsdatascience.com/another-conformal-way-to-predict-probability-distributions-fcc63e78680d

Not sure how easy to implement it would be for time series though.

### Use case

It would be really helpful for downstream simulation to optimize decision making.

**Comment by EtienneT** [comment]
Crepes seems to be the only package that implement Conformal Predictive System used to calculate full conformal prediction distribution: https://crepes.readthedocs.io/en/latest/crepes_nb_wrap.html#Conformal-Predictive-Systems-(CPS)

**Comment by jmoralez** [comment]
Hey @EtienneT, sorry for the late reply. We store the conformity scores on the `_cs_df` attribute, which has the scores by serie and horizon. You can get it with the following:

```python
import lightgbm as lgb
from datasetsforecast.m4 import M4, M4Info
from mlforecast import MLForecast
from mlforecast.utils import PredictionIntervals

# load data
group = 'Hourly'
info = M4Info[group]
horizon = info.horizon
await M4.async_download('data', group=group)
df, *_ = M4.load(directory='data', group=group)
df['ds'] = df['ds'].astype('int')

# train
n_windows = 4
n_series = df['unique_id'].nunique()
fcst = MLForecast(
    models=[lgb.LGBMRegressor(verbosity=-1)],
    freq=1,
    lags=[24],
)
fcst.fit(df, prediction_intervals=PredictionIntervals(n_windows=n_windows, h=horizon))

# extract scores
lgb_scores = fcst._cs_df['LGBMRegressor'].to_numpy().reshape(n_windows, n_series, horizon)
lgb_scores.shape
# (4, 414, 48)
```
We use these scores to compute the intervals here https://github.com/Nixtla/mlforecast/blob/55e9b504ba37fa4dbb7fd092bfd4654540eb5da7/mlforecast/forecast.py#L62-L69

Please let us know if this helps.
