### ISSUE TITLE
Add more examples about distributed forecast with Ray and PySpark

### ISSUE THREAD

**Issue by juanitorduz** [Nixtla/mlforecast#209]
### Description

Hi! The documentation from the `statsforecast` package is really great! In particular, I have found the examples with Ray and PySpark really nice, like https://nixtla.github.io/statsforecast/docs/how-to-guides/spark.html. 

Is there a similar example in the `mlforecast` docs? I did not find it.

I have read are collaborating with the `fugue` project. It owuld be great to have an analogous example

https://fugue-tutorials.readthedocs.io/tutorials/integrations/ecosystem/nixtla.html

### Use case

At the moment I am very working in forecasting at scale, and I would like to test `mlforecast`. I have already gotten good results with `statsforecast` :)

**Comment by jmoralez** [comment]
Hey. The documentation for the distributed interface is currently [here](https://nixtla.github.io/mlforecast/distributed.forecast.html), there are sections for dask, spark and ray.

Please let us know if you feel something's missing. Off the top of my head I think we're missing installation instructions, if you run `pip install "mlforecast[distributed]"` it'll install dask, spark, ray, xgboost and lightgbm, which may be more than you want.

**Comment by jmoralez** [comment]
Yes, the only difference is in the data setup. mlforecast assumes that each partition holds full series, e.g. serie100 is only in partition 5. This is achieved in different ways depending on the framework, but the documentation shows how to do it for each one, except for ray where I think it isn't possible and the only way to do it is with the `num_partitions` argument of `DistributedMLForecast`. Feel free to reopen if you struggle to find something else.

**Comment by jmoralez** [comment]
Oh also the models are different per framework. We currently support LightGBM and XGBoost for dask, spark and ray, and the path to each module is like `mlforecast.distributed.models.<framework>.<model_lib>`.
