### ISSUE TITLE
[Model] Getting issue with instantiating SparkLGBMForecast 

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/mlforecast#253]
### What happened + What you expected to happen

Getting error when instantiating SparkLGBMForecast. 

![image](https://github.com/Nixtla/mlforecast/assets/12494156/3b672777-e272-409b-b929-ac6c1f6200bd)

Error message: 
TypeError: 'JavaPackage' object is not callable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-1328766050816477> in <module>
      2 from xgboost.spark import SparkXGBRegressor
      3 from mlforecast.distributed.models.spark.xgb import SparkXGBForecast
----> 4 models = [SparkLGBMForecast()]
      5 #           SparkXGBForecast()]
      6 

/databricks/spark/python/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    112             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113         self._input_kwargs = kwargs
--> 114         return func(self, **kwargs)
    115     return wrapper
    116 

/local_disk0/.ephemeral_nfs/envs/pythonEnv-7caa5693-c402-498c-89e6-d2aabf9ef09b/lib/python3.8/site-packages/synapse/ml/lightgbm/LightGBMRegressor.py in __init__(self, java_obj, alpha, baggingFraction, baggingFreq, baggingSeed, binSampleCount, boostFromAverage, boostingType, catSmooth, categoricalSlotIndexes, categoricalSlotNames, catl2, chunkSize, dataRandomSeed, dataTransferMode, defaultListenPort, deterministic, driverListenPort, dropRate, dropSeed, earlyStoppingRound, executionMode, extraSeed, featureFraction, featureFractionByNode, featureFractionSeed, featuresCol, featuresShapCol, fobj, improvementTolerance, initScoreCol, isEnableSparse, isProvideTrainingMetric, labelCol, lambdaL1, lambdaL2, leafPredictionCol, learningRate, matrixType, maxBin, maxBinByFeature, maxCatThreshold, maxCatToOnehot, maxDeltaStep, maxDepth, maxDrop, maxNumClasses, maxStreamingOMPThreads, metric, microBatchSize, minDataInLeaf, minDataPerBin, minDataPerGroup, minGainToSplit, minSumHessianInLeaf, modelString, monotoneConstraints, monotoneConstraintsMethod, monotonePenalty, negBaggingFraction, numBatches, numIterations, numLeaves, numTasks, numThreads, objective, objectiveSeed, otherRate, parallelism, passThroughArgs, posBaggingFraction, predictDisableShapeCheck, predictionCol, referenceDataset, repartitionByGroupingColumn, samplingMode, samplingSubsetSize, seed, skipDrop, slotNames, timeout, topK, topRate, tweedieVariancePower, uniformDrop, useBarrierExecutionMode, useMissing, useSingleDatasetMode, validationIndicatorCol, verbosity, weightCol, xGBoostDartMode, zeroAsMissing)
    404         super(LightGBMRegressor, self).__init__()
    405         if java_obj is None:
--> 406             self._java_obj = self._new_java_obj("com.microsoft.azure.synapse.ml.lightgbm.LightGBMRegressor", self.uid)
    407         else:
    408             self._java_obj = java_obj

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

TypeError: 'JavaPackage' object is not callable

Works for the other ones (SparkXGBForecast, SparkXGBRegressor)
![image](https://github.com/Nixtla/mlforecast/assets/12494156/33d6c991-b9ca-45a8-877e-33b2a603d6f1)

### Versions / Dependencies

0.10.0 

### Reproduction script

from mlforecast.distributed.models.spark.lgb import SparkLGBMForecast
models = [SparkLGBMForecast()] 

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @iamyihwa. Which SynapseML and Databricks runtime versions are you using? I'm able to import this correctly with the following:
* SynapseML: com.microsoft.azure:synapseml_2.12:0.11.3-spark3.3
* Databricks: 12.2 (Spark 3.3.2 ,Scala 2.12)

**Comment by iamyihwa** [comment]
Hi @jmoralez   

Databricks: 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12)
SynapseML : Changed to the version you are using 
`spark = (
    SparkSession
    .builder    
    .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.11.3-spark3.3")    #  "com.microsoft.azure:synapseml_2.12:0.10.2")
    .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven")
    .getOrCreate()
)`

but still getting the same error as above.

**Comment by jmoralez** [comment]
Since your runtime has spark 3.2 you should use `com.microsoft.azure:synapseml_2.12:0.11.3` as stated [here](https://microsoft.github.io/SynapseML/docs/Get%20Started/Install%20SynapseML/#databricks).

**Comment by iamyihwa** [comment]
Thanks @jmoralez 

I have just tried with that option 

``` 
spark = (
    SparkSession
    .builder    
    .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.11.3")    #  "com.microsoft.azure:synapseml_2.12:0.10.2")
    .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven")
    .getOrCreate()
)

from mlforecast.distributed.models.spark.lgb import SparkLGBMForecast
models = [SparkLGBMForecast()]
from xgboost.spark import SparkXGBRegressor
from mlforecast.distributed.models.spark.xgb import SparkXGBForecast
models.append(SparkXGBForecast())

models.append(SparkXGBRegressor())
``` 

However, am getting the same error 

<img width="764" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/5c49751e-29de-4803-bd70-288cfafc8a89">



```

**Comment by jmoralez** [comment]
Since you're using databricks it's probably best to install that in the Libraries section of your cluster, for example
![image](https://github.com/Nixtla/mlforecast/assets/8473587/9f23261b-beb2-4dfc-8e25-c828a591f806)

If you keep getting that error can you please try running `from synapse.ml.lightgbm import LightGBMRegressor` and if that fails opening an issue in https://github.com/microsoft/SynapseML? They can probably be of more help with this.
