### ISSUE TITLE
[ETC] No module name mlforecast.feature_engineering

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/mlforecast#264]
### What happened + What you expected to happen

Was getting error ModuleNotFoundError: no module named mlforecast.feature_engineering
![image](https://github.com/Nixtla/mlforecast/assets/12494156/a2f8dd08-4a5b-42e5-8653-b6994f9abbcb)

### Versions / Dependencies

0.10.0

### Reproduction script

from mlforecast.feature_engineering import transform_exog

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey. This will be part of the next release. If you're able to install from github you can use it now.

**Comment by iamyihwa** [comment]
Oh I see @jmoralez  good to know! Thanks! Since it was appearing in the tutorial, somehow I assumed that it was already in the official release. 
Thanks ! Will try with that!
