### ISSUE TITLE
[MLForecast] lag_transforms with different features packages 

### ISSUE THREAD

**Issue by Chaptyziok** [Nixtla/mlforecast#284]
### Description

Currently only window_ops lagged features like rolling_mean or expanding_min can be added as lag_transforms to the model. The idea is to allow for use of tsfresh or tsfeatures inside of the lag_transforms.

**Comment by jmoralez** [comment]
Hey @Chaptyziok, thanks for using mlforecast. Those libraries produce aggregations, how are you looking to use them? If you want to use the single value by serie that they produce you could join them with your dataframe and use them as static features.

**Comment by Chaptyziok** [comment]
@jmoralez Actually I want to create rolled features outside of the MLForecast, but I would like to pass them with lags. From what I know MLForecast uses recursive approach so they can also be predicted one step ahead and used as future features.

**Comment by jmoralez** [comment]
I see. I think you can do the same as in [this guide](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/transforming_exog.html).

**Comment by Chaptyziok** [comment]
@jmoralez Exactly, thank you for providing this guide.

**Comment by jmoralez** [comment]
Nice. Can we close this issue then?

**Comment by Chaptyziok** [comment]
@jmoralez Yes, please close this issue.
