### ISSUE TITLE
Dynamic features for training

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#297]
### Description

Hi! I want to add dynamic covariate features for training time series data. I noticed that mlforecast supports adding static features to the model. Can I add dynamic features currently?

**Comment by jmoralez** [comment]
Hey. [This guide](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/exogenous_features.html#use-existing-exogenous-features) covers that.
