### ISSUE TITLE
AutoDifferences, AutoSeasonalityAndDifferences result in "AttributeError: 'NoneType' object has no attribute 'AutoDifferences'"

### ISSUE THREAD

**Issue by jack-fletch** [Nixtla/mlforecast#312]
### What happened + What you expected to happen

As soon as I call either of these functions I get "AttributeError: 'NoneType' object has no attribute 'AutoDifferences'". I was looking through the source code and I believe it may be because the function's `return` statement is missing. I could be totally wrong about this being the issue.

### Versions / Dependencies

0.11.7

### Reproduction script

from mlforecast.target_transforms import AutoDifferences
AutoDifferences(max_diffs = 3)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @jack-fletch, thanks for using mlforecast. These new transformations require the `coreforecast` package, which will be required in the next version but it seems that I messed up the imports. If you want to use them you can just `pip install 'coreforecast>=0.0.4'` and that should work.

**Comment by jack-fletch** [comment]
Thanks! Everything works now. Appreciate it!
