### ISSUE TITLE
get performance on training set

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#320]
### Description

Hello, I have followed the instructions to compute the prediction performance on the validation dataset. I wonder how I can get the performance on the training set using Mlforcast?

**Comment by jmoralez** [comment]
Hey @kkckk1110, thanks for using mlforecast. You can run `fit` setting `fitted=True` and then use the [forecast_fitted_values](https://nixtlaverse.nixtla.io/mlforecast/forecast.html#mlforecast-forecast-fitted-values) method.
