### ISSUE TITLE
[MLForecast] Add the possibility to pass custom parameters to the fit function

### ISSUE THREAD

**Issue by helderPereira22** [Nixtla/mlforecast#322]
### Description

Enable the ability to pass custom parameters (for instance with kwargs) for the fit function of the model

### Use case

For instance, to use the Overfitting detector of the Catboost algorithm (where we pass 'early_stopping_rounds' to the fit function)

**Comment by jmoralez** [comment]
Hey @helderPereira22, thanks for using mlforecast. I believe you can achieve that following [this guide](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/custom_training.html).

Please let us know if that doesn't work for you.

**Comment by helderPereira22** [comment]
Hello @jmoralez!

I think it works! But do I lose any of the Nixtla capabilities by doing this?

**Comment by jmoralez** [comment]
All we do with the trained models is call predict, so it should work exactly in the same way.

**Comment by helderPereira22** [comment]
Hello @jmoralez,

For instance, adopting the custom training approach you recommended means I wouldn't have the ability to employ Conformal Prediction for creating prediction intervals. Therefore, it seems I would be sacrificing this feature by not applying the .fit method provided by Nixtla.

Could you take this into account?
