### ISSUE TITLE
Accept list of models in forecast

### ISSUE THREAD

**Issue by jmoralez** [Nixtla/mlforecast#33]
## Summary

Make it possible to accept a list of models when using the forecast object. 

## Motivation

This would allow to re-use the processed series and compute predictions more efficiently. Also allows this library to be more in sync with [statsforecast](https://github.com/Nixtla/statsforecast).

## Description

Something along the lines of `Forecast([Model1(), Model2()], ts)` where the `predict` method will return a dataframe with as many columns as models.

## References

https://nixtla.github.io/statsforecast/core.html#statsforecast `models` argument.

**Comment by baggiponte** [comment]
Isn't this already happening? The example shows that:

```
import lightgbm as lgb
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor

models = [
    lgb.LGBMRegressor(),
    xgb.XGBRegressor(),
    RandomForestRegressor(random_state=0),
]

fcst = Forecast(models, ts)
```
