### ISSUE TITLE
[Custom Training] Add custom training for Cross Validation

### ISSUE THREAD

**Issue by VictorMichonIntelcom** [Nixtla/mlforecast#334]
### Description

The current version of MLForecast does not support applying custom weights during cross-validation training. The custom training feature described in the documentation is only available for the final model training, not for the cross-validation process.

This is a limitation of the current implementation, as the cross-validation in MLForecast is designed to use the default training procedure without any customization. The cross-validation is used for model selection and hyperparameter tuning, where the ability to apply custom weights may be beneficial for certain use cases.

### Use case

If I want to apply some weight on samples during training, in order to improve my forecasts on a given set of dates/periods, I need to use the custom training feature you explained in this guide https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/custom_training.html. 
However, in the case I want to perform model selection over cross validation scores of multiple models, I need to be able to reproduce the same customed training during cross validation. This is where I am currently blocked, as the current version of MLForecast does not support applying custom weights during the cross-validation process.

**Comment by jmoralez** [comment]
Hey @VictorMichonIntelcom, sorry for the late reply. We're evaluating adding a `weight_col` argument to the methods that would then forward that to `sample_weight` during `fit`. In the meantime, can you try the approach described [here](https://github.com/Nixtla/mlforecast/discussions/437#discussioncomment-11080697)? That should work for using weights in cross validation.

**Comment by jmoralez** [comment]
v0.14.0 added the `weight_col` argument to fit and cross_validation. More custom training stuff can be done by overriding the fit method of the models, which would be model-specific and I believe is better done by the user.

Closing since the weight is a very common case and that's already fixed. Feel free to reopen if using scikit-learn pipelines doesn't solve your use case for custom training.
