### ISSUE TITLE
SHAP with exogenous features

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#342]
### What happened + What you expected to happen

Hello! I hope to use shap to interpret my model, but I came across the following issue.

File ~/miniforge3/lib/python3.9/site-packages/mlforecast/forecast.py:689, in MLForecast.predict(self, h, before_predict_callback, after_predict_callback, new_df, level, X_df, ids)
    686 else:
    687     ts = self.ts
--> 689 forecasts = ts.predict(
    690     models=self.models_,
    691     horizon=h,
    692     before_predict_callback=before_predict_callback,
    693     after_predict_callback=after_predict_callback,
    694     X_df=X_df,
    695     ids=ids,
    696 )
    697 if level is not None:
    698     if self._cs_df is None:

File ~/miniforge3/lib/python3.9/site-packages/mlforecast/core.py:733, in TimeSeries.predict(self, models, horizon, before_predict_callback, after_predict_callback, X_df, ids)
    731 try:
    732     if getattr(self, "max_horizon", None) is None:
--> 733         preds = self._predict_recursive(
    734             models=models,
    735             horizon=horizon,
    736             before_predict_callback=before_predict_callback,
    737             after_predict_callback=after_predict_callback,
    738             X_df=X_df,
    739         )
    740     else:
    741         preds = self._predict_multi(
    742             models=models,
    743             horizon=horizon,
    744             before_predict_callback=before_predict_callback,
    745             X_df=X_df,
    746         )

File ~/miniforge3/lib/python3.9/site-packages/mlforecast/core.py:606, in TimeSeries._predict_recursive(self, models, horizon, before_predict_callback, after_predict_callback, X_df)
    604 for i, (name, model) in enumerate(models.items()):
    605     self._predict_setup()
--> 606     for _ in range(horizon):
    607         new_x = self._get_features_for_next_step(X_df)
    608         if before_predict_callback is not None:

TypeError: 'DataFrame' object cannot be interpreted as an integer

### Versions / Dependencies

MACOS

### Reproduction script

model = MLForecast(models=models,freq='MS',lags=[1,12]) 
model.fit(train, id_col='unique_id', time_col='ds', target_col='sales',  static_features=[],fitted=True)

import shap
X = train.drop(columns=['unique_id', 'ds', 'sales'])
X100 = shap.utils.sample(X, 100)
explainer = shap.Explainer(model.predict, X100)
shap_values = explainer(X, max_evals=600)

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Have you read [this guide](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/analyzing_models.html#shap)?

**Comment by kkckk1110** [comment]
Yes, and the codes are exactly following the guide

**Comment by jmoralez** [comment]
That passes the linear regression model to the explainer, you're passing the MLForecast object.

**Comment by kkckk1110** [comment]
Many thanks to your kind reply! I have another question that, I incorporate lag features in the model setup but do not have them in my dataset. In this case, how could I obtain the shap results?

model = MLForecast(models=models_app,freq='MS',lags=[1,12])

**Comment by kkckk1110** [comment]
Many thanks to your kind replies!
