### ISSUE TITLE
[core/auto]  Cannot reproduce Hyperparameter Tuning tutorial due to an import error on v0.13.0

### ISSUE THREAD

**Issue by ds-qst** [Nixtla/mlforecast#359]
### What happened + What you expected to happen

When trying to import from mlforecast.auto in a notebook I receive an ImportError: cannot import name '_get_model_name' from 'mlforecast.core'

Trying to reproduce the hyperparameter tuning guide (https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/hyperparameter_optimization.html#imports)

### Versions / Dependencies

mlforecast is 0.13.0.

### Reproduction script

import os
import tempfile

import lightgbm as lgb
import optuna
import pandas as pd
from datasetsforecast.m4 import M4, M4Evaluation, M4Info
from sklearn.linear_model import Ridge
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder
from utilsforecast.plotting import plot_series

from mlforecast import MLForecast
from mlforecast.auto import (
    AutoLightGBM,
    AutoMLForecast,
    AutoModel,
    AutoRidge,
    ridge_space,
)
from mlforecast.lag_transforms import ExponentiallyWeightedMean, RollingMean

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey. How did you install the package? It's very unlikely that it has an incompatibility within itself, you may have mixed installs.

**Comment by ds-qst** [comment]
> Hey. How did you install the package? It's very unlikely that it has an incompatibility within itself, you may have mixed installs.

Just installed with a normal "pip install mlforecast". I also did some test imports:

from mlforecast.core import _name_models
from mlforecast.core import Freq

Does not return an error, but 
from mlforecast.core import _get_model_name

returns ImportError: cannot import name '_get_model_name' from 'mlforecast.core'

**Comment by jmoralez** [comment]
It's here https://github.com/Nixtla/mlforecast/blob/3eb62908cdb58d2c73684ecdb5f9c0aca767242b/mlforecast/core.py#L105

Is that the full error?

**Comment by ds-qst** [comment]
Yes, that's why I'm confused.

The full error, when running the import from  the tutorial is:
     20 
     21 from . import MLForecast
---> 22 from .core import Freq, _get_model_name, _name_models
     23 from .lag_transforms import ExponentiallyWeightedMean, RollingMean
     24 from .optimization import _TrialToConfig, mlforecast_objective

ImportError: cannot import name '_get_model_name' from 'mlforecast.core' (/home/<redacted>/venv/lib/python3.10/site-packages/mlforecast/core.py)

I checked the core.py already, but no luck trying to import it. 
![image](https://github.com/Nixtla/mlforecast/assets/173423249/749a82e8-05f2-4e18-ae71-2c9caf8241ec)

**Comment by jmoralez** [comment]
Hmm, I'm not able to reproduce the issue. I just opened that notebook in [colab](https://colab.research.google.com/github/Nixtla/mlforecast/blob/main/nbs/docs/how-to-guides/hyperparameter_optimization.ipynb), added `%pip install datasetsforecast mlforecast` as the top cell and ran all without a problem.

**Comment by bryanwhiting** [comment]
I've just had this same issue. v0.13.2

<img width="722" alt="image" src="https://github.com/user-attachments/assets/56e26d5a-bcca-4d26-bf3f-548b912bb763">

**Comment by bryanwhiting** [comment]
I had pre-installed `AutoGluon`, which had different package requirements. I did 

```
! pip install --upgrade mlforecast
! pip install --upgrade utilsforecast
```
and now i can import properly
