### ISSUE TITLE
Nested cross-validation

### ISSUE THREAD

**Issue by Chaptyziok** [Nixtla/mlforecast#393]
### Description

Currently mlforecast supports the standard cross-validation. It would be nice to have also a nested cross-validation.

**Comment by jmoralez** [comment]
Hey. Can you describe what that would look like for a single serie? From what I can tell the nested cross validation creates folds from the same samples using a different permutation, how would that work for time series?

**Comment by Chaptyziok** [comment]
@jmoralez I will send a PR with the proposed changes.
