### ISSUE TITLE
Categorical Feature Handling

### ISSUE THREAD

**Issue by webert6** [Nixtla/mlforecast#401]
Hello,

I am looking to verify how categorical features are handled for models that support categorical features. I've found things here and there like [this](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/training_with_numpy.html#preprocess-method) and [this](https://github.com/Nixtla/mlforecast/blob/fcf5dc5df5721100d211aeca122ef2c3f0b1ea1e/mlforecast/optimization.py#L91-L92), but I'm looking for more definitive answers. Additionally, I'd like to test different variations of categorical feature handling and how I can adjust the parameters would be great to know.

Thanks!

**Comment by jmoralez** [comment]
We don't do anything special, we just pass them through. If you provide categorical columns and a model that doesn't support them you'll most likely get an error.
