### ISSUE TITLE
Model Training in Multi Time-Series: Single vs. Separate Models

### ISSUE THREAD

**Issue by mavillan** [Nixtla/mlforecast#402]
### Description

Hi all,

It's not clear to me how model training is performed internally. In particular, I want to know what happens in a multi time-series problem. Specifically, do you 1) train a single model for all the series, or 2) train a separate model for each series? If it's like 1), do you use the `unique_id` as a feature for the model?

**Comment by jmoralez** [comment]
Hey. A single model is trained on all series. The id isn't used as a feature unless you explicitly ask for it by setting `static_features=[your_id_col]`

**Comment by mavillan** [comment]
Hi @jmoralez , thanks for the prompt response! Perfect, it would be great to add that somewhere in the README/documentation

**Comment by mavillan** [comment]
Hi @jmoralez , thanks for the prompt response! Perfect, it would be great to add that somewhere in the README/documentation
