### ISSUE TITLE
[distributed] Error when saving model object

### ISSUE THREAD

**Issue by maxi-marufo** [Nixtla/mlforecast#404]
### What happened + What you expected to happen

I'm getting the following error when calling `model.save` with a `DistributedMLForecast` object:

```
_1 _State.RUNNING -> _State.FAILED  'NoneType' object has no attribute 'ncores'
```

### Versions / Dependencies

Python 3.10.0
`dask = {version = "^2024.2.1", extras = ["dataframe"]}`
`distributed = "^2024.2.1"`

### Reproduction script

```
from dask.distributed import Client
from mlforecast.distributed import DistributedMLForecast
from mlforecast.distributed.models.dask.lgb import DaskLGBMForecast
from mlforecast.lag_transforms import RollingMean
from pandas.tseries.offsets import DateOffset


client = Client(n_workers=1, threads_per_worker=threads_per_worker)  
mlforecast_parameters = {
    "models": [DaskLGBMForecast()],
    "freq": DateOffset(minutes=15),
    "lags": map(lambda x: int(x * 4), [1 / 4, 24, 24 * 7]),
    "lag_transforms": {
        4 * 24: [(RollingMean(window_size=4 * 24))],
        4 * 24 * 7: [(RollingMean(window_size=4 * 24 * 7))],
    },
    "date_features": ["dayofweek", "month"],
    "num_threads": num_threads,
    "engine": client,
}
mlforecast_model = DistributedMLForecast(**mlforecast_parameters)
mlforecast_model.fit(mlforecast_data)
client.close()
mlforecast_model.save("path")

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey, thanks for using mlforecast. Can you please include the full stacktrace? It'll help a lot to see which part of the code is triggering this.

**Comment by maxi-marufo** [comment]
> Hey, thanks for using mlforecast. Can you please include the full stacktrace? It'll help a lot to see which part of the code is triggering this.

Sure! Here it is:

```
  File "/usr/local/lib/python3.10/site-packages/app/model/mlforecast.py", line 136, in save_model
    mlforecast_model.save("path")
  File "/usr/local/lib/python3.10/site-packages/mlforecast/distributed/forecast.py", line 668, in save
    dummy_df = fa.transform(
  File "/usr/local/lib/python3.10/site-packages/fugue/workflow/api.py", line 174, in transform
    dag.run(make_execution_engine(engine, conf=engine_conf, infer_by=[df]))
  File "/usr/local/lib/python3.10/site-packages/fugue/workflow/workflow.py", line 1604, in run
    raise ex.with_traceback(ctb)
  File "/usr/local/lib/python3.10/site-packages/distributed/client.py", line 3949, in nthreads
    return self.sync(self.scheduler.ncores, workers=workers, **kwargs)
AttributeError: 'NoneType' object has no attribute 'ncores'
```

**Comment by jmoralez** [comment]
Ah, I think it's this line: `client.close()`. Why are you closing the client before saving the object? It still needs because it has the partitions info.

**Comment by maxi-marufo** [comment]
Hi Jose! Yes! That was it! After writing my message here I realized that too. I was using `client.close()` as I was previously saving the model by serializing it manually (without using the `.save` method) and then I realized that could be the problem, which it was! Thanks for your help!
