### ISSUE TITLE
Hyper-Parameter Optimization for multivariate forecasting

### ISSUE THREAD

**Issue by masadshoaib** [Nixtla/mlforecast#405]
### Description

Hi,

Can you please share an example of how to do hyper-parameter optimization when one has exogenous variables? 

The MLForecast allows for a simple way to do so by declaring the variables such as static_features, etc. But in the AutoMLForecast, how can one declare these features? If I try including this as an argument to the fit function of AutoMLForecast, it gives me an error citing that this is not a valid argument.

Looking forward to hearing soon.

Thanks!

**Comment by jmoralez** [comment]
Hey. The `static_features `argument is part of `MLForecast.fit`, so you have to provide it through the `fit_config` of the auto models. You can find an example [here ](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/hyperparameter_optimization.html#tuning-fit-parameters) which tunes whether or not the id should be included as a feature.

**Comment by masadshoaib** [comment]
Clears it up. Thanks :)
