### ISSUE TITLE
[AutoMlforecast] AutoMlforecast evaluate the performance of a model with cross_validation

### ISSUE THREAD

**Issue by Poterix13** [Nixtla/mlforecast#407]
### Description

I have a problem: I want to evaluate the performance of models using cross-validation, but I'm encountering errors.
If there's another way of evaluating, how can I implement it?

```python
# Model dictionary
models ={
        'xgb':AutoXGBoost(),
        #'naive': Naive(),
        'lgbm': AutoLightGBM(),
        'lin_reg': AutoLinearRegression(),
        'ridge': AutoRidge(),
        'rf': AutoRandomForest()
    }

from mlforecast.target_transforms import Differences, LocalStandardScaler
auto_mlf = AutoMLForecast(
    models = models, 
    freq='MS',  
    season_length=12,
    num_threads=2
    
)


crossvalidationh24_df = auto_mlf.cross_validation(
    df=data_train,
    h=24,
    step_size=24,
    n_windows=2
)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[22], [line 1](vscode-notebook-cell:?execution_count=22&line=1)
----> [1](vscode-notebook-cell:?execution_count=22&line=1) crossvalidationh24_df = auto_mlf.cross_validation(
      [2](vscode-notebook-cell:?execution_count=22&line=2)     df=data_train,
      [3](vscode-notebook-cell:?execution_count=22&line=3)     h=2[4](vscode-notebook-cell:?execution_count=22&line=4),
      4     step_size=24,
      [5](vscode-notebook-cell:?execution_count=22&line=5)     n_windows=2
      [6](vscode-notebook-cell:?execution_count=22&line=6) )

AttributeError: 'AutoMLForecast' object has no attribute 'cross_validation'

----------------------------------------------------------------------------
```

**Comment by jmoralez** [comment]
Hey @Poterix13, thanks for using mlforecast. The `AutoMLForecast.fit` method performs cross validation to score the trials and choose the best model. You can then [inspect the results](https://nixtlaverse.nixtla.io/mlforecast/docs/how-to-guides/hyperparameter_optimization.html#accessing-the-optimization-results), where each trial's score is the average error in the cross validation folds.

**Comment by Poterix13** [comment]
Hello @jmoralez thank you for your help. I've finally seen how to proceed, but I have a problem: when I run auto_mlf.results_['lgbm'].best_trial.user_attrs['config'] i get this result: 
----------------------------------------------------------
{'model_params': {'bagging_freq': 1,
  'learning_rate': 0.05,
  'verbosity': -1,
  'n_estimators': 255,
  'lambda_l1': 1.9038135910385762e-06,
  'lambda_l2': 0.00015732471573476155,
  'num_leaves': 10,
  'feature_fraction': 0.5794847918227599,
  'bagging_fraction': 0.5551875705821525,
  'objective': 'l1'},
 'mlf_init_params': {'lags': [12],
  'target_transforms': [<mlforecast.target_transforms.GlobalSklearnTransformer at 0x29fd853c6b0>,
   <mlforecast.target_transforms.Differences at 0x29fd85f7d10>,
   <mlforecast.target_transforms.LocalStandardScaler at 0x29fd85f7a70>],
  'lag_transforms': {1: [ExponentiallyWeightedMean(alpha=0.9)],
   12: [RollingMean(min_samples=1, window_size=12)],
   24: [RollingMean(min_samples=1, window_size=12)]},
  'date_features': None,
  'num_threads': 2},
 'mlf_fit_params': {}}
----------------------------------------------------------------

I don't understand 0x29fd853c6b0 or 0x29fd85f7a70 value ???

**Comment by jmoralez** [comment]
That's the memory address of the objects. They don't have a nice repr (way to tell python how to print them) but they're just some transformations that are applied to the target before training the models, in this case (a log, then difference and then scaling).

**Comment by Poterix13** [comment]
I thought it was the transformation function argument

**Comment by Poterix13** [comment]
Thanks @jmoralez

**Comment by Poterix13** [comment]
Hello @jmoralez , I have a concern
before optimisation 

mlf = MLForecast(
    models = models, 
    freq='MS',  
    target_transforms=[Differences([1, 2]), LocalStandardScaler()],
    lags=[1], 
    lag_transforms={  
        1: [ExpandingMean()],
        12: [RollingMean(window_size=12)],
    },

    date_features=['month','year']
)


After optimisation on obtained the following parameters for one model

{'model_params': {'bagging_freq': 1,
  'learning_rate': 0.05,
  'verbosity': -1,
  'n_estimators': 307,
  'lambda_l1': 5.14861122776246,
  'lambda_l2': 8.904450147868902,
  'num_leaves': 54,
  'feature_fraction': 0.5354348890921041,
  'bagging_fraction': 0.6463970157202594,
  'objective': 'l2'},
 'mlf_init_params': {'lags': range(12, 25, 12),
  'target_transforms': [<mlforecast.target_transforms.GlobalSklearnTransformer at 0x1f65d3c0f20>,
   <mlforecast.target_transforms.Differences at 0x1f65d256f30>,
   <mlforecast.target_transforms.LocalStandardScaler at 0x1f65d3c24e0>],
  'lag_transforms': {1: [ExponentiallyWeightedMean(alpha=0.9)]},
  'date_features': ['month', 'year'],
  'num_threads': 5},
 'mlf_fit_params': {}}

I want to adapt my code according to these new parameters and then do a cross-validation to evaluate performance on the training set, but I can't figure out how to arrange the parameters and the values they take. 

I want to do this because after optimisation I have no information about the performance of the model on the training set. 

need your assistance

**Comment by jmoralez** [comment]
```python
config = auto_mlf.results_['lgbm'].best_trial.user_attrs['config']
fcst = MLForecast(models=[LGBMRegressor(**config['model_params']), **config['mlf_init_params])
cv_res = fcst.cross_validation(your_data, fitted=True, **config['mlf_fit_params'])
cv_fitted = fcst.cross_validation_fitted_values()
```

**Comment by Poterix13** [comment]
Thanks @jmoralez
