### ISSUE TITLE
pylance warning - Argument of type "list[LGBMRegressor]" cannot be assigned to parameter "models" of type "Models" in function "init"

### ISSUE THREAD

**Issue by sumamjose** [Nixtla/mlforecast#411]
### Description

I'm encountering a type mismatch issue when passing a list of models (regressors) to the MLForecast class. The documentation states that the models parameter can be either a single regressor or a list of regressors as in https://github.com/Nixtla/mlforecast/blob/main/mlforecast/forecast.py#L126. However, when passing a list of models or the model alone, I receive a type error indicating that Argument of type "list[LGBMRegressor]" cannot be assigned to parameter "models" of type "Models" in function "__init__"

Python 3.10.12
mlforecast 0.13.4

According to the documentation:

Parameters
-----------
models : regressor or list of regressors
          Models that will be trained and used to compute the forecasts.

Sample code: 

----------------------------------------------------------------------------------
```python
# Import necessary libraries
from mlforecast import MLForecast
import lightgbm as lgb
from sklearn.linear_model import LinearRegression
import pandas as pd

# Create a simple DataFrame to simulate data
train_df = pd.DataFrame({
    'ds': pd.date_range(start='2020-01-01', periods=100, freq='D'),
    'y': range(100),
})

# Define a list of models
models = [
    lgb.LGBMRegressor(random_state=0, verbosity=-1),
    LinearRegression(),
]

# Initialize MLForecast with the list of models
try:
    fcst = MLForecast(models=models, freq='D')
    print("Model initialized successfully.")
except TypeError as e:
    print(f"Encountered an error: {e}")
```
--------------------------------------------------------------------------

the above code works fine without warning, but when using 

```python
models = [lgb.LGBMRegressor(random_state=0, verbosity=-1)]
```

or
```python
models = lgb.LGBMRegressor(random_state=0, verbosity=-1) 
```

it gives respective pylance warnings as below in vscode:

```python
Argument of type "list[LGBMRegressor]" cannot be assigned to parameter "models" of type "Models" in function "__init__"
  Type "list[LGBMRegressor]" is incompatible with type "Models"
    "list[LGBMRegressor]" is incompatible with "BaseEstimator"
    "list[LGBMRegressor]" is incompatible with "List[BaseEstimator]"
      Type parameter "_T@list" is invariant, but "LGBMRegressor" is not the same as "BaseEstimator"
      Consider switching from "list" to "Sequence" which is covariant
    "list[LGBMRegressor]" is incompatible with "Dict[str, BaseEstimator]"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)

or 

Argument of type "LGBMRegressor" cannot be assigned to parameter "models" of type "Models" in function "__init__"
  Type "LGBMRegressor" is incompatible with type "Models"
    "LGBMRegressor" is incompatible with "BaseEstimator"
    "LGBMRegressor" is incompatible with "List[BaseEstimator]"
    "LGBMRegressor" is incompatible with "Dict[str, BaseEstimator]"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

Could you please look into why that is happening despite the documentation?

**Comment by jmoralez** [comment]
Hey @sumamjose, thanks for using mlforecast. This seems to be related to LightGBM, it seems that the linter picks up the dummy classes defined in the compat module instead of the scikit learn ones. Here's a minimal example (without mlforecast) where we can see the issue:
![Screenshot from 2024-10-29 20-03-06](https://github.com/user-attachments/assets/79c666ce-cb8f-494c-9cf9-35bb08eefb8f)

Feel free to open an issue there, it seems that what XGBoost does (defining those dummy base classes as `object` instead) works.
