### ISSUE TITLE
[mlflow flavor] Distributed of MLForecast doesn't support for load model 

### ISSUE THREAD

**Issue by Aeim** [Nixtla/mlforecast#414]
### What happened + What you expected to happen

When I use mlforecast.flavor to load distributed version of model, it show the error that `No such file or directory: '/local_disk0/repl_tmp_data/ReplId-19203-35577-8/tmpta101dhm/model/mlforecast-model/ts.pkl'` because the model of distributed is save in name as `_base_ts.pkl ` It may be change it to run to be success.

### Versions / Dependencies

mlforecast==0.13.4

### Reproduction script

`loaded_model = mlforecast.flavor.load_model(model_uri=model_uri)
`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey. Whats your expectation here? For the distributed model to be saved into a local one? Or support loading it for distributed inference?
