### ISSUE TITLE
[AutoML] Custom training for AutoML

### ISSUE THREAD

**Issue by ncooder** [Nixtla/mlforecast#424]
### Description

Is there a way to use LightGBM with sample_weight for the AutoML approach? I want to also add rolling statistics, exogenous features, transformed target etc. I know it is possible in MLforecast, but I am not sure if this is possible for the AutoMLforecast.

**Comment by jmoralez** [comment]
Hey. The easiest way to set the weights is to define a class that inherits from LightGBM and override the fit and predict methods to use the weights. For the features you have to set them in the `init_config`, you can also tune them there if you want.

```python
import numpy as np
from lightgbm import LGBMRegressor
from mlforecast.auto import AutoMLForecast, AutoModel, lightgbm_space
from utilsforecast.data import generate_series

class LGBMWeights(LGBMRegressor):
    def fit(self, df, y):
        weights = df['weight']
        X = df.drop(columns='weight')
        return super().fit(X=X, y=y, sample_weight=weights)

    def predict(self, df):
        return super().predict(X=df.drop(columns='weight'))

series = generate_series(5)
series['weight'] = np.random.rand(series.shape[0])
auto_mlf = AutoMLForecast(
    models={'lgb': AutoModel(LGBMWeights(), lightgbm_space)},
    freq='D',
    init_config=lambda trial: {'lags': [1, 2]},
    fit_config=lambda trial: {'static_features': []},
)
auto_mlf.fit(series, n_windows=2, h=14, num_samples=5)
```

**Comment by ncooder** [comment]
@jmoralez Thank you! That solves the problem.
