### ISSUE TITLE
[AutoML] Independent control of the backtest window size and forecast horizon

### ISSUE THREAD

**Issue by ncooder** [Nixtla/mlforecast#425]
### Description

Please add a new parameter for AutoMLforecast that will disconnect the forecast horizon and horizon for backtest windows.

**Comment by jmoralez** [comment]
Hey. Do you mean the `step_size`? i.e. by how many timestamps the train end advances in each window? #419 added it to the objective function so it'd just be a matter of adding it to the AutoMLforecast class

**Comment by ncooder** [comment]
@jmoralez Yes, I was referring exactly to this. Thank you!
