### ISSUE TITLE
ValueError: The time column ('ds') should have either timestamps or integers, got 'object'.

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#427]
### What happened + What you expected to happen

data.loc[i,'ds'] = pd.to_datetime(data.loc[i,'ds'], format='%Y-%m')

then when I fit the model, the error occurred.

ValueError: The time column ('ds') should have either timestamps or integers, got 'object'.

### Versions / Dependencies

 mlforecast-0.13.4
pandas-1.5.3

### Reproduction script

for i in range(0,len(data)):
    data.loc[i,'ds'] = pd.to_datetime(data.loc[i,'ds'], format='%Y-%m')

models = [XGBRegressor(random_state=42, n_estimators=params['n_estimators'],
                       learning_rate=params['learning_rate'], max_depth=params['max_depth'],
                min_child_weight=params['min_child_weight'], subsample=params['subsample'], 
                       colsample_bytree=params['colsample_bytree'])]
model = MLForecast(models=models,freq='MS') 
model.fit(pd.concat([train,valid],axis=0), id_col='unique_id', time_col='ds', target_col='sales',static_features=[],fitted=True)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Why are you converting each entry instead of the whole column? That seems to make pandas unable to know that the whole column is made of timestamps

**Comment by kkckk1110** [comment]
Oh! I previously used data.loc[:,'ds'] = pd.to_datetime(data['ds'], format='%Y-%m'), it also had errors.
But after I changed into data['ds'] = pd.to_datetime(data['ds'], format='%Y-%m'), the code run successfully. Thanks a lot!
