### ISSUE TITLE
Lag features not computing properly in distributed forecast

### ISSUE THREAD

**Issue by joeackers** [Nixtla/mlforecast#438]
### What happened + What you expected to happen

Lag features are returning nulls when they should not be, the issue appears to only affect the distributed forecast module. Running the exact same code as I did yesterday is now returning nulls. 

To test I created a basic weekly dataframe (see screenshot 1 below) and got second screenshot as an output

![Screenshot 2024-10-29 at 11 01 47](https://github.com/user-attachments/assets/1a6084ae-ba8d-401e-ab94-64a66e3286a0)
![Screenshot 2024-10-29 at 11 04 03](https://github.com/user-attachments/assets/15b493e2-4eba-4fb6-9e4b-e7bd1cfef9a0)

### Versions / Dependencies

Using latest version 0.13.5

### Reproduction script

```python
from datetime import datetime, timedelta
from pyspark.sql.types import StructType, StructField, IntegerType, DateType

schema = StructType([
    StructField("unique_id", IntegerType(), False),
    StructField("SalesQty", IntegerType(), False),
    StructField("WeekStartDate", DateType(), False)
])

# unique_id is static, dates increase weekly, and SalesQty has a simple pattern
test_data = [
    (1, 100, datetime(2023, 1, 1) + timedelta(weeks=i)) for i in range(20)  # 20 weeks of data
]


test_df = spark.createDataFrame(test_data, schema)

fcst = DistributedMLForecast(
    models=[],
    freq='W-SAT',
    lags=[1,2],
)

test_df = test_df.withColumn('WeekStartDate', F.col('WeekStartDate').cast('timestamp'))
fcst.preprocess(test_df, 'unique_id', 'WeekStartDate',  'SalesQty', static_features=[], dropna=False).show()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @joeackers, thanks for using mlforecast. As outlined in the [documentation](https://nixtlaverse.nixtla.io/mlforecast/docs/getting-started/quick_start_distributed.html#data-setup-2), you need to make sure that each serie is in a single partition:

> For spark, the data must be a pyspark DataFrame. You need to make sure that each time serie is only in one partition (which you can do using repartitionByRange, for example)

**Comment by joeackers** [comment]
@jmoralez Thanks for this, yes the repartition is working now.
