### ISSUE TITLE
How the training of global models realized?

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#440]
### Description

Hello, I am using mlforecast to train a global forecasting model and reaching an exciting performance. However, I have some questions about the training details of global models. Specifically, I am using XGBoost for forecasting. When training a global model, does the trainer automatically input the unique_id as additional features? Or, does it simply aggregate the data from different series and train on the whole dataset without any additional features? 
Thanks a lot for your attention.

**Comment by jmoralez** [comment]
Hey. The id isn't used as a feature unless you explicitly ask for it by setting `static_features=[your_id_col]`. The features that are used to train are the ones you define in the constructor: lags, lag transforms, date features. The id is just used to differentiate between the series to compute the features and apply some target transformations.
