### ISSUE TITLE
[forecast: fit, lag_transforms, SeasonalRollingMean] double free or corruption (out) error  

### ISSUE THREAD

**Issue by hugoguh** [Nixtla/mlforecast#450]
### What happened + What you expected to happen

I get a ```double free or corruption (out)```error in linux when trying to fit a model using `SeasonalRollingMean` as lag_transform.
I do not get that error on macOS, nor if I use `RollingMean` instead of SeasonalRollingMean, nor if I use `coreforecast==0.0.12`

### Versions / Dependencies

OS: [debian](https://hub.docker.com/_/debian)
python: [Python 3.11.10](https://github.com/docker-library/python/blob/37a6827e0b7a9ef099cfdec5de305e3d4cea7331/3.11/slim-bookworm/Dockerfile)
mlforecast==0.15.0
coreforecast==0.0.14

### Reproduction script

```python

import lightgbm as lgb
from mlforecast import MLForecast
from mlforecast.lag_transforms import SeasonalRollingMean
from mlforecast.utils import generate_daily_series

def main():
    data = generate_daily_series(10)
    fcst = MLForecast(
        models=[lgb.LGBMRegressor()],
        freq='D',
        lag_transforms={
            56: [SeasonalRollingMean(season_length=7, window_size=4, min_samples=2)]
        },
    )
    fcst.fit(data)

if __name__ == "__main__":
    main()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey. Thanks a lot for the detailed report, I'm able to reproduce the issue and will work on a fix.

**Comment by jmoralez** [comment]
Fixed by https://github.com/Nixtla/coreforecast/pull/62, will make a release later today. Thanks for reporting!
