### ISSUE TITLE
nb Forecast doens't run in latest pypi version

### ISSUE THREAD

**Issue by Gabrielcidral1** [Nixtla/mlforecast#51]
This nb doesn't work with latest pypi mlforecast version (installing via pip install mlforecast, version 0.2.0) https://github.com/Nixtla/mlforecast/blob/6ac01ec16e1da2d04ca8ea9e4d4a2ed173f7c534/nbs/forecast.ipynb

To make it work, I had to specifically pass the same package as in github: `pip install git+https://github.com/Nixtla/mlforecast.git#egg=mlforecast`

**Comment by jmoralez** [comment]
Hi. We've made some breaking changes in the dev version, we're going to make a release soon. In the meantime you can use the [notebook from the v0.2.0 branch](https://github.com/Nixtla/mlforecast/blob/v0.2.0/nbs/forecast.ipynb) as reference or install from github as you're currently doing.

**Comment by jmoralez** [comment]
We've released [v0.3.0](https://pypi.org/project/mlforecast/0.3.0/) which should fix this, please let us know if the issue persists.
