### ISSUE TITLE
mlforecast for multivariate time series analysis

### ISSUE THREAD

**Issue by MariaBocsa** [Nixtla/mlforecast#62]
Hello,

I want to use "mlforecast" library for my Multivariate Time Series problem and I want to know how could I add new features, like holidays or temperature, to the dataset besides 'lags' and 'date_features'. 
Below is flow configuration:
```
`fcst = Forecast(
    models=model,
    freq='W-MON',
    lags=[1,2,3,4,5,6,7,8],
    date_features=['month', 'week']
)
`
```
Is there a way to add exogenous variables to the training process? I could not find relevant information to be able to do this.

Thank you!

**Comment by pietroppeter** [comment]
[m5 notebook](https://www.kaggle.com/code/lemuz90/m5-mlforecast-eval) contains examples of some of the things you mention

**Comment by MariaBocsa** [comment]
I will check it. Thank you, @pietroppeter!

**Comment by pietroppeter** [comment]
you are welcome, have a good day! note that I am just a random user of the library, maybe the maintainers will have better suggestions. :)

**Comment by jmoralez** [comment]
Closing this since it seems solved. Feel free to reopen if you have further doubts.
